name: GitHub Actions Runner
version: "1.0.8"
slug: github_actions_runner
description: Self-hosted GitHub Actions runner for Home Assistant
url: https://github.com/skille/home-assistant-github-runner-add-on
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
boot: auto
hassio_api: true
hassio_role: default
ingress: true
ingress_port: 8099
panel_icon: mdi:github
webui: "[PROTO:ssl]://[HOST]:[PORT:8099]"
options:
  repo_url: ""
  runner_token: ""
  runner_name: ""
  debug_logging: false
schema:
  repo_url: str
  runner_token: str
  runner_name: str?
  debug_logging: bool
