name: GitHub Actions Runner
version: "1.6.5"
slug: github_actions_runner
description: Self-hosted GitHub Actions runner for Home Assistant
url: https://github.com/skille/home-assistant-github-runner-add-on
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
boot: auto
hassio_api: true
hassio_role: default
apparmor: false
panel_icon: mdi:github
map:
  - timezone:ro
  - share:rw
  - addon_configs:rw
options:
  repo_url: ""
  runner_token: ""
  github_pat: ""
  runner_name: ""
  runner_labels: ""
  debug_logging: false
schema:
  repo_url: str
  runner_token: str?
  github_pat: password?
  runner_name: str?
  runner_labels: str?
  debug_logging: bool
